### ISSUE TITLE
Can't get the price of BNB

### ISSUE THREAD

**Issue by s951736** [heyajohnny/cryptoinfo#12]
I start to use Cryptoinfo today, I can use it to get the price ETH and BTC, but I can't get the price of BNB.
BTC, ETH, BNB are all I want, thanks!

Here is the code from configuration.yaml
```
sensor:
  - platform: cryptoinfo
    id: "eth price"
    cryptocurrency_name: "ethereum"
    currency_name: "usd"
    update_frequency: 1
  - platform: cryptoinfo
    id: "bnb price"
    cryptocurrency_name: "binancecoin"
    currency_name: "usd"
    update_frequency: 1
  - platform: cryptoinfo
    id: "btc price"
    cryptocurrency_name: "bitcoin"
    currency_name: "usd"
    update_frequency: 1
```
