### ISSUE TITLE
feature request: total ERC20 holdings

### ISSUE THREAD

**Issue by R5fan** [heyajohnny/cryptoinfo#13]
Heya Johnny,

Love your addon. But what I would love even more is having a HA sensor that contains the USD (or EUR) value of all my ethereum + erc20 tokens. For instance:
https://etherscan.io/tokenholdings?a=0x281055afc982d96fab65b3a49cac8b878184cb16
(no, not my address :) ).

I cant find an API that does this, even etherscan API as far as I can tell does not support this, weirdly, which probably only leaves scraping the website?

**Comment by heyajohnny** [comment]
You could use a template like this. Just add a sensor to it, for every cryptocurrency you have in 'cryptoinfo'.

This example combines the total value of 3 sensors into this 1 template sensor:
```yaml
  - platform: template
    sensors:
      crypto_total:
        value_template: "{{
          ( states('sensor.cryptoinfo_main_wallet_ethereum_eur') | float | round(2)) +
          ( states('sensor.cryptoinfo_bitcoin_eur') | float | round(2)) +
          ( states('sensor.cryptoinfo_cardano_eur') | float | round(2))
          }}"
        unit_of_measurement: '€'
        friendly_name: Total value of all my cryptocurrencies
```

Reading an Etherscan address with it's values is not a part of the Coingecko API, so I won't be adding it to this project.  So the only solution I see is the one up here :point_up:
