### ISSUE TITLE
ethereum crypto is not working

### ISSUE THREAD

**Issue by thibdj** [heyajohnny/cryptoinfo#40]
hello, It seems that the ethereum crypto is not working. It works with all other cryptos.
  
  An extract of my home assistant conf :
  
  
  - platform: cryptoinfo
    id: ""           
    cryptocurrency_name: "bitcoin" 
    currency_name: "eur"            
    unit_of_measurement: "\u200b"   
    multiplier: 1                   
    update_frequency: 15 

  - platform: cryptoinfo
    id: ""           
    cryptocurrency_name: "ethereum" 
    currency_name: "eur"            
    unit_of_measurement: "\u200b"   
    multiplier: 1                   
    update_frequency: 15

**Comment by heyajohnny** [comment]
@thibdj 
Works fine when I use your config:
```
sensor:
- platform: cryptoinfo
  id: ""
  cryptocurrency_name: "ethereum"
  currency_name: "eur"
  unit_of_measurement: "\u200b"
  multiplier: 1
  update_frequency: 15

```
![image](https://github.com/heyajohnny/cryptoinfo/assets/20553716/cc80f933-6561-4df2-9b3e-274df3ea004a)

**Comment by thibdj** [comment]
@heyajohnny ty for your feedback. I tried another config by addding also cardano, and it's working for BTC and cardano but still not working with Eth, very strange...

  - platform: cryptoinfo
    id: ""           
    cryptocurrency_name: "bitcoin" 
    currency_name: "eur"            
    unit_of_measurement: "\u200b"   
    multiplier: 1                   
    update_frequency: 15 

  - platform: cryptoinfo
    id: ""           
    cryptocurrency_name: "ethereum" 
    currency_name: "eur"            
    unit_of_measurement: "\u200b"   
    multiplier: 1                   
    update_frequency: 15
    
  - platform: cryptoinfo
    id: ""           
    cryptocurrency_name: "cardano" 
    currency_name: "eur"            
    unit_of_measurement: "\u200b"   
    multiplier: 1                   
    update_frequency: 15

**Comment by heyajohnny** [comment]
@thibdj I've just tested this config:
```
sensor:
- platform: cryptoinfo
  id: ""
  cryptocurrency_name: "bitcoin"
  currency_name: "eur"
  unit_of_measurement: "\u200b"
  multiplier: 1
  update_frequency: 15
- platform: cryptoinfo
  id: ""
  cryptocurrency_name: "ethereum"
  currency_name: "eur"
  unit_of_measurement: "\u200b"
  multiplier: 1
  update_frequency: 15
- platform: cryptoinfo
  id: ""
  cryptocurrency_name: "cardano"
  currency_name: "eur"
  unit_of_measurement: "\u200b"
  multiplier: 1
  update_frequency: 15
```
And works like a charm. Are you sure you haven't got a typo somewhere in your configuration.yaml? And what's the Home Assistant and cryptoinfo version you are using?
