### ISSUE TITLE
Can't get the price of Zilliqa

### ISSUE THREAD

**Issue by 19leva89** [heyajohnny/cryptoinfo#41]
Good day, thank you for your integration! But for some reason I don’t get the price for zilliqa. At the same time, everything is fine for bitcoin
  
```
sensor:
    - platform: cryptoinfo
      cryptocurrency_name: "zilliqa"
      currency_name: "usd"
      unit_of_measurement: "\u200b"
      multiplier: 1
      update_frequency: 45

    - platform: cryptoinfo
      cryptocurrency_name: "bitcoin"
      currency_name: "usd"
      unit_of_measurement: "\u200b"
      multiplier: 1
      update_frequency: 45
```
