### ISSUE TITLE
Error fetching update from coingecko: 0 - response status: 429 - Too Many Requests

### ISSUE THREAD

**Issue by 1mfaasj** [heyajohnny/cryptoinfo#45]
Hi,
I've got this error multiple times a day:
`Error fetching update from coingecko: 0 - response status: 429 - Too Many Requests`

Do you know what the api quota is? how many requests are we allowed te make?

I'm using this config and already changed update_frequency to 15 (instead of 1) but unfortunately the error stays.
the frequency is in minutes right? you know this for sure?
```
sensor:
  - platform: cryptoinfo
    id: "wallet"
    cryptocurrency_name: "bitcoin"
    currency_name: "usd"
    unit_of_measurement: "$"
    multiplier: 1
    update_frequency: 15
  - platform: cryptoinfo
    id: "wallet"
    cryptocurrency_name: "ethereum"
    currency_name: "usd"
    unit_of_measurement: "$"
    multiplier: 1
    update_frequency: 15
  - platform: cryptoinfo
    id: "wallet"
    cryptocurrency_name: "polygon-ecosystem-token"
    currency_name: "usd"
    unit_of_measurement: "$"
    multiplier: 1
    update_frequency: 15
```
